### ISSUE TITLE
Great idea, here is my first contribution

### ISSUE THREAD

**Issue by pitchke** [gpunktschmitz/mediawiki-updater#1]
Dear Guenther,

I found your script few days ago searching to ... automate few mediawiki upgrades and it motivates me to bring some suggestions and adapt to my use cases and generic solutions.
Allow me to attach the current script which shows most changes in itself and as comments in code.
I just saw that you updated your current script, thanks again ;-), I will have a look and continue to improve it if I can (I am not a Shell script expert).

[mediawiki-updater v2017-11-21.sh.txt](https://github.com/gpunktschmitz/mediawiki-updater/files/1491735/mediawiki-updater.v2017-11-21.sh.txt)

Pleased to contribute ...

**Comment by gpunktschmitz** [comment]
hi Pierre,
Thanks for the contribution! Much appreciated!

Just by today (because of serious issues with several MediaWiki-installations) I updated the bash script to a new process (see [README.md](https://github.com/gpunktschmitz/mediawiki-updater/blob/master/README.md)). The old update process resulted in malfunctions like: resetting passwords would no longer work or some extensions stopped working. So now I move the old installation to a backup path, extract the new release and copy skins, extensions, LocaSettings.php and images to the new release.

Now, instead of using the github repo I now download the .tar.gz including the vendor folder/dependencies.

Also I fixed some stupid things (where you certainly notice I am also not a shell script expert) like the pushd/podp you also noted.

Thanks again for sharing!

KR
Guenther
